### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by morgan-hu** [panhaoyu/itasca-stub#1]
您好，您可以给出一些简单实例吗，像我这样的小白选手，真的有点无从下手，谢谢

**Comment by panhaoyu** [comment]
很抱歉我没打算把这个做成正经的开源项目，只是个人代码库的简单分享。希望你知道这个代码库是解决什么问题的，就是在pycharm里面写fish的时候可以有自动补全。我觉得有这个需求的人并不多。

**Comment by morgan-hu** [comment]
好吧，谢谢，我是一名岩土工程研究生，在学习PFC，有点python基础，希望以后有机会能多交流，谢谢
